parameters:
#    ts_settings.example.class: TS\SettingsBundle\Example

services:
    ts_settings.pre_action:
        class: TS\SettingsBundle\EventListener\PreActionListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
