imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

gregwar_captcha:
    disabled: true

web_profiler:
    toolbar: true
    #intercept_redirects: true

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: false

swiftmailer:
    delivery_address: sjoerdsmink+mailtest@gmail.com
    disable_delivery: true
    #spool: { type: memory }

services:
    ts_site_mails.twig.extension.debug:
        class:        Twig_Extension_Debug
        tags:
             - { name: 'twig.extension' }

ruudk_payment_mollie:
    api_key:  test_pqxK6rl8hJBtwW7spnOJXAazF4EQWP

#bit_google:
#    callback_url: http://www.isbtplanner.com/app_dev.php/login_check_google?google=true