<?php

namespace TS\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{
	public function getAllSpecialFiles()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT f FROM TSSiteBundle:File f WHERE f.specialType != '' ORDER BY f.fileName ASC"
            )
            ->getResult();
    }
}
