parameters:
#    ts_control.example.class: TS\ControlBundle\Example

services:
#    ts_control.example:
#        class: %ts_control.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    ts_control.pre_action:
        class: TS\ControlBundle\EventListener\PreActionListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
